/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated/comunidade'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedAulaLessonIdRouteImport } from './routes/_authenticated/aula.$lessonId'
import { Route as AuthenticatedModulosIndexRouteImport } from './routes/_authenticated/modulos.index'
import { Route as AuthenticatedModulosModuleIdRouteImport } from './routes/_authenticated/modulos.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAulaLessonIdRoute =
  AuthenticatedAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulosIndexRoute =
  AuthenticatedModulosIndexRouteImport.update({
    id: '/modulos/',
    path: '/modulos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulosModuleIdRoute =
  AuthenticatedModulosModuleIdRouteImport.update({
    id: '/modulos/$moduleId',
    path: '/modulos/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/modulos/$moduleId': typeof AuthenticatedModulosModuleIdRoute
  '/modulos/': typeof AuthenticatedModulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/modulos/$moduleId': typeof AuthenticatedModulosModuleIdRoute
  '/modulos': typeof AuthenticatedModulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/_authenticated/modulos/$moduleId': typeof AuthenticatedModulosModuleIdRoute
  '/_authenticated/modulos/': typeof AuthenticatedModulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/comunidade'
    | '/inicio'
    | '/materiais'
    | '/ofertas'
    | '/suporte'
    | '/aula/$lessonId'
    | '/modulos/$moduleId'
    | '/modulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/comunidade'
    | '/inicio'
    | '/materiais'
    | '/ofertas'
    | '/suporte'
    | '/aula/$lessonId'
    | '/modulos/$moduleId'
    | '/modulos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/comunidade'
    | '/_authenticated/inicio'
    | '/_authenticated/materiais'
    | '/_authenticated/ofertas'
    | '/_authenticated/suporte'
    | '/_authenticated/aula/$lessonId'
    | '/_authenticated/modulos/$moduleId'
    | '/_authenticated/modulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aula/$lessonId': {
      id: '/_authenticated/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulos/': {
      id: '/_authenticated/modulos/'
      path: '/modulos'
      fullPath: '/modulos/'
      preLoaderRoute: typeof AuthenticatedModulosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulos/$moduleId': {
      id: '/_authenticated/modulos/$moduleId'
      path: '/modulos/$moduleId'
      fullPath: '/modulos/$moduleId'
      preLoaderRoute: typeof AuthenticatedModulosModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAulaLessonIdRoute: typeof AuthenticatedAulaLessonIdRoute
  AuthenticatedModulosModuleIdRoute: typeof AuthenticatedModulosModuleIdRoute
  AuthenticatedModulosIndexRoute: typeof AuthenticatedModulosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAulaLessonIdRoute: AuthenticatedAulaLessonIdRoute,
  AuthenticatedModulosModuleIdRoute: AuthenticatedModulosModuleIdRoute,
  AuthenticatedModulosIndexRoute: AuthenticatedModulosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
